#ifndef NW4R_PUBLIC_SND_H
#define NW4R_PUBLIC_SND_H

#include <nw4r/snd/snd_AxManager.h>
#include <nw4r/snd/snd_AxVoice.h>
#include <nw4r/snd/snd_AxVoiceManager.h>
#include <nw4r/snd/snd_AxfxImpl.h>
#include <nw4r/snd/snd_Bank.h>
#include <nw4r/snd/snd_BankFile.h>
#include <nw4r/snd/snd_BasicPlayer.h>
#include <nw4r/snd/snd_BasicSound.h>
#include <nw4r/snd/snd_Channel.h>
#include <nw4r/snd/snd_ChannelManager.h>
#include <nw4r/snd/snd_Common.h>
#include <nw4r/snd/snd_DisposeCallback.h>
#include <nw4r/snd/snd_DisposeCallbackManager.h>
#include <nw4r/snd/snd_DvdSoundArchive.h>
#include <nw4r/snd/snd_EnvGenerator.h>
#include <nw4r/snd/snd_ExternalSoundPlayer.h>
#include <nw4r/snd/snd_FrameHeap.h>
#include <nw4r/snd/snd_FxBase.h>
#include <nw4r/snd/snd_FxChorus.h>
#include <nw4r/snd/snd_FxDelay.h>
#include <nw4r/snd/snd_FxReverbHi.h>
#include <nw4r/snd/snd_FxReverbHiDpl2.h>
#include <nw4r/snd/snd_InstancePool.h>
#include <nw4r/snd/snd_Lfo.h>
#include <nw4r/snd/snd_MemorySoundArchive.h>
#include <nw4r/snd/snd_MmlParser.h>
#include <nw4r/snd/snd_MmlSeqTrack.h>
#include <nw4r/snd/snd_MmlSeqTrackAllocator.h>
#include <nw4r/snd/snd_MoveValue.h>
#include <nw4r/snd/snd_NandSoundArchive.h>
#include <nw4r/snd/snd_PlayerHeap.h>
#include <nw4r/snd/snd_RemoteSpeaker.h>
#include <nw4r/snd/snd_RemoteSpeakerManager.h>
#include <nw4r/snd/snd_SeqFile.h>
#include <nw4r/snd/snd_SeqPlayer.h>
#include <nw4r/snd/snd_SeqSound.h>
#include <nw4r/snd/snd_SeqSoundHandle.h>
#include <nw4r/snd/snd_SeqTrack.h>
#include <nw4r/snd/snd_SeqTrackAllocator.h>
#include <nw4r/snd/snd_Sound3DActor.h>
#include <nw4r/snd/snd_Sound3DListener.h>
#include <nw4r/snd/snd_Sound3DManager.h>
#include <nw4r/snd/snd_SoundActor.h>
#include <nw4r/snd/snd_SoundArchive.h>
#include <nw4r/snd/snd_SoundArchiveFile.h>
#include <nw4r/snd/snd_SoundArchiveLoader.h>
#include <nw4r/snd/snd_SoundArchivePlayer.h>
#include <nw4r/snd/snd_SoundHandle.h>
#include <nw4r/snd/snd_SoundHeap.h>
#include <nw4r/snd/snd_SoundInstanceManager.h>
#include <nw4r/snd/snd_SoundPlayer.h>
#include <nw4r/snd/snd_SoundStartable.h>
#include <nw4r/snd/snd_SoundSystem.h>
#include <nw4r/snd/snd_SoundThread.h>
#include <nw4r/snd/snd_StrmChannel.h>
#include <nw4r/snd/snd_StrmFile.h>
#include <nw4r/snd/snd_StrmPlayer.h>
#include <nw4r/snd/snd_StrmSoundHandle.h>
#include <nw4r/snd/snd_Task.h>
#include <nw4r/snd/snd_TaskManager.h>
#include <nw4r/snd/snd_TaskThread.h>
#include <nw4r/snd/snd_Util.h>
#include <nw4r/snd/snd_Voice.h>
#include <nw4r/snd/snd_VoiceManager.h>
#include <nw4r/snd/snd_WaveFile.h>
#include <nw4r/snd/snd_WaveSound.h>
#include <nw4r/snd/snd_WaveSoundHandle.h>
#include <nw4r/snd/snd_WsdFile.h>
#include <nw4r/snd/snd_WsdPlayer.h>
#include <nw4r/snd/snd_adpcm.h>

#endif
