#ifndef RP_AUDIO_SND_STATIC_MGR_H
#define RP_AUDIO_SND_STATIC_MGR_H
#include <Pack/types_pack.h>

#include <egg/audio.h>

#include <nw4r/snd.h>

#include <revolution/WPAD.h>

//! @addtogroup rp_audio
//! @{

/**
 * @brief Static-lifetime sound archive manager
 */
class RPSndStaticMgr : public EGG::ArcPlayer {
public:
    /**
     * @brief Constructor
     */
    RPSndStaticMgr();

    /**
     * @brief Destructor
     */
    virtual ~RPSndStaticMgr(); // at 0x8

    /**
     * @brief Updates the state of the sound player
     */
    virtual void calc(); // at 0x34

    /**
     * @brief Mounts the static sound archive
     *
     * @return Success
     */
    bool setupArchive();

    /**
     * @brief Starts a sound effect through the main output and the specified
     * player's remote output
     *
     * @param id Sound effect ID
     * @param player Player index
     */
    void startSe(u32 id, s32 player);

private:
    /**
     * @brief Sound start task
     */
    struct StartTask {
        //! Whether this task structure is in use
        bool valid; // at 0x0
        //! Time-out threshold
        u16 timeOut; // at 0x2
        u16 unk4;
        //! Player output line flag
        u32 playerFlag; // at 0x8
        u32 unkC;
        //! Sound ID
        u32 id; // at 0x10
    };

    //! Task time-out threshold
    static const int TIMEOUT = 120;

private:
    /**
     * @brief Configures the main and remote output volumes for the specified
     * sound
     *
     * @param playerFlag Player output line flags
     */
    void setRemoteSend(u32 playerFlag);

private:
    //! Active sound handle
    nw4r::snd::SoundHandle mSoundHandle; // at 0x5B4
    //! Sound effect tasks
    StartTask mStartTasks[WPAD_MAX_CONTROLLERS]; // at 0x5B8

    //! Static sound archive binary (generated by dtk)
    static u8 sStaticSoundArchive[];
};

//! @}

#endif
